export const WARLOCK_PACT_SLOTS = {
  1:  { slots: 1, slotLevel: 1 }, 2:  { slots: 2, slotLevel: 1 },
  3:  { slots: 2, slotLevel: 2 }, 4:  { slots: 2, slotLevel: 2 },
  5:  { slots: 3, slotLevel: 3 }, 6:  { slots: 3, slotLevel: 3 },
  7:  { slots: 4, slotLevel: 4 }, 8:  { slots: 4, slotLevel: 4 },
  9:  { slots: 4, slotLevel: 5 }, 10: { slots: 4, slotLevel: 5 },
  11: { slots: 3, slotLevel: 5 }, 12: { slots: 3, slotLevel: 5 },
  13: { slots: 3, slotLevel: 5 }, 14: { slots: 3, slotLevel: 5 },
  15: { slots: 3, slotLevel: 5 }, 16: { slots: 3, slotLevel: 5 },
  17: { slots: 4, slotLevel: 5 }, 18: { slots: 4, slotLevel: 5 },
  19: { slots: 4, slotLevel: 5 }, 20: { slots: 4, slotLevel: 5 },
}

export const WLOCK_INVOCATIONS = [
  { name: 'Agonizing Blast', minLevel: 1, priority: 'SIEMPRE', pact: null, source: 'PHB', desc: '+CAR a cada rayo de Eldritch Blast. Obligatoria en toda build.' },
  { name: 'Armor of Shadows', minLevel: 1, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Mage Armor a voluntad sin gastar slot. Excelente en niveles bajos.' },
  { name: 'Ascendant Step', minLevel: 9, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Levitate a voluntad sobre ti. Movilidad vertical útil en mapas complejos.' },
  { name: 'Beast Speech', minLevel: 1, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Speak with Animals a voluntad. Valor narrativo y exploración.' },
  { name: 'Beguiling Influence', minLevel: 1, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: '+Competencia en Engaño y Persuasión. Domina pilares sociales.' },
  { name: 'Bewitching Whispers', minLevel: 7, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Compulsion 1/día con slot. Control de posicionamiento en masa.' },
  { name: 'Book of Ancient Secrets', minLevel: 5, priority: 'ALTA', pact: 'Tomo', source: 'PHB', desc: '(Tomo) Rituales sin slot: Identify, Detect Magic, Find Familiar...' },
  { name: 'Chains of Carceri', minLevel: 15, priority: 'SITUACIONAL', pact: 'Cadena', source: 'PHB', desc: '(Cadena) Hold Monster a celestiales/fiends/elementales sin gastar slot.' },
  { name: 'Devil\'s Sight', minLevel: 1, priority: 'ALTA', pact: null, source: 'PHB', desc: 'Visión en oscuridad mágica. Combina con Darkness para ventaja.' },
  { name: 'Dreadful Word', minLevel: 7, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Confusion 1/día usando slot. Bueno contra grupos.' },
  { name: 'Eldritch Sight', minLevel: 1, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Detect Magic a voluntad. Utilidad permanente fuera de combate.' },
  { name: 'Eldritch Spear', minLevel: 1, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Aumenta alcance de Eldritch Blast. Sniper arcano.' },
  { name: 'Eyes of the Rune Keeper', minLevel: 1, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Lees toda escritura. Muy útil en investigación.' },
  { name: 'Fiendish Vigor', minLevel: 1, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'False Life a voluntad en nivel 1. Mitiga daño al inicio del día.' },
  { name: 'Gaze of Two Minds', minLevel: 1, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Percibes a través de otro objetivo. Exploración y scouting.' },
  { name: 'Lifedrinker', minLevel: 12, priority: 'ALTA', pact: 'Hoja', source: 'PHB', desc: '(Hoja) +CAR al daño por golpe. Brutal en Hexblade melee.' },
  { name: 'Mask of Many Faces', minLevel: 1, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Disguise Self ilimitado. Infiltración y juego social.' },
  { name: 'Master of Myriad Forms', minLevel: 15, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Alter Self a voluntad para adaptación total.' },
  { name: 'Minions of Chaos', minLevel: 9, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Conjure Elemental 1/día con slot. Potente pero costoso.' },
  { name: 'Mire the Mind', minLevel: 5, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Slow 1/día con slot. Gran debuff de control.' },
  { name: 'Misty Visions', minLevel: 1, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Silent Image a voluntad. Señuelos y control visual.' },
  { name: 'One with Shadows', minLevel: 5, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Invisibilidad estática en penumbra/oscuridad. Emboscadas.' },
  { name: 'Otherworldly Leap', minLevel: 9, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Jump a voluntad en ti. Movilidad táctica.' },
  { name: 'Repelling Blast', minLevel: 1, priority: 'ALTA', pact: null, source: 'PHB', desc: 'Empuja 10 pies por rayo de EB. Control de mapa sin slots.' },
  { name: 'Sign of Ill Omen', minLevel: 5, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Bestow Curse 1/día con slot. Debuff muy fuerte.' },
  { name: 'Thief of Five Fates', minLevel: 1, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Bane 1/día usando slot. Soporte/debuff temprano.' },
  { name: 'Thirsting Blade', minLevel: 5, priority: 'ALTA', pact: 'Hoja', source: 'PHB', desc: '(Hoja) Ataque extra. Imprescindible para Hexblade melee.' },
  { name: 'Visions of Distant Realms', minLevel: 15, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Arcane Eye a voluntad. Reconocimiento de élite.' },
  { name: 'Voice of the Chain Master', minLevel: 1, priority: 'MEDIA', pact: 'Cadena', source: 'PHB', desc: '(Cadena) Percibe/habla por el familiar a gran distancia.' },
  { name: 'Whispers of the Grave', minLevel: 9, priority: 'SITUACIONAL', pact: null, source: 'PHB', desc: 'Speak with Dead a voluntad.' },
  { name: 'Witch Sight', minLevel: 15, priority: 'MEDIA', pact: null, source: 'PHB', desc: 'Ves forma real de cambiaformas e ilusiones.' },
  { name: 'Aspect of the Moon', minLevel: 1, priority: 'MEDIA', pact: 'Tomo', source: 'XGE', desc: '(Tomo) No necesitas dormir; gran utilidad de campaña.' },
  { name: 'Cloak of Flies', minLevel: 5, priority: 'SITUACIONAL', pact: null, source: 'XGE', desc: 'Aura ofensiva/amenazante cercana mientras está activa.' },
  { name: 'Eldritch Smite', minLevel: 5, priority: 'ALTA', pact: 'Hoja', source: 'XGE', desc: '(Hoja) Burst fuerte y derribo con slot en impacto.' },
  { name: 'Gift of the Ever-Living Ones', minLevel: 1, priority: 'MEDIA', pact: 'Cadena', source: 'XGE', desc: '(Cadena) Curación sobre ti al máximo de dado.' },
  { name: 'Ghostly Gaze', minLevel: 7, priority: 'SITUACIONAL', pact: null, source: 'XGE', desc: 'Ves a través de objetos sólidos por breve tiempo.' },
  { name: 'Gift of the Depths', minLevel: 5, priority: 'SITUACIONAL', pact: null, source: 'XGE', desc: 'Respirar bajo agua y velocidad de nado; nicho acuático.' },
  { name: 'Grasp of Hadar', minLevel: 1, priority: 'ALTA', pact: null, source: 'XGE', desc: 'Atrae 10 pies con EB. Excelente para focus fire.' },
  { name: 'Improved Pact Weapon', minLevel: 1, priority: 'ALTA', pact: 'Hoja', source: 'XGE', desc: '(Hoja) Mejora arma del pacto y facilita estilo marcial.' },
  { name: 'Lance of Lethargy', minLevel: 1, priority: 'MEDIA', pact: null, source: 'XGE', desc: 'Ralentiza con EB. Kiteo y control de distancia.' },
  { name: 'Maddening Hex', minLevel: 5, priority: 'MEDIA', pact: null, source: 'XGE', desc: 'Daño psíquico en área al objetivo maldito/hexeado.' },
  { name: 'Relentless Hex', minLevel: 7, priority: 'MEDIA', pact: null, source: 'XGE', desc: 'Teleport corto al objetivo de Hex/maldición.' },
  { name: 'Shroud of Shadow', minLevel: 15, priority: 'ALTA', pact: null, source: 'XGE', desc: 'Invisibility a voluntad. Sigilo extremo.' },
  { name: 'Tomb of Levistus', minLevel: 5, priority: 'ALTA', pact: null, source: 'XGE', desc: 'Reacción defensiva brutal contra picos de daño.' },
  { name: 'Trickster\'s Escape', minLevel: 7, priority: 'SITUACIONAL', pact: null, source: 'XGE', desc: 'Freedom of Movement 1/día con slot.' },
  { name: 'Eldritch Mind', minLevel: 1, priority: 'ALTA', pact: null, source: 'TCE', desc: 'Ventaja para mantener concentración. Muy estable.' },
  { name: 'Far Scribe', minLevel: 5, priority: 'SITUACIONAL', pact: 'Tomo', source: 'TCE', desc: '(Tomo) Comunicación mágica escrita con nombres inscritos.' },
  { name: 'Gift of the Protectors', minLevel: 9, priority: 'ALTA', pact: 'Tomo', source: 'TCE', desc: '(Tomo) Evita caída a 0 PG una vez por descanso largo.' },
  { name: 'Investment of the Chain Master', minLevel: 9, priority: 'ALTA', pact: 'Cadena', source: 'TCE', desc: '(Cadena) Potencia masivamente al familiar en combate.' },
  { name: 'Rebuke of the Talisman', minLevel: 1, priority: 'MEDIA', pact: 'Talismán', source: 'TCE', desc: '(Talismán) Reacción para empujar a quien golpea al portador.' },
  { name: 'Protection of the Talisman', minLevel: 7, priority: 'MEDIA', pact: 'Talismán', source: 'TCE', desc: '(Talismán) Mejora defensiva al portador del talismán.' },
  { name: 'Bond of the Talisman', minLevel: 12, priority: 'SITUACIONAL', pact: 'Talismán', source: 'TCE', desc: '(Talismán) Teletransporte al portador del talismán.' },
  { name: 'Undying Servitude', minLevel: 5, priority: 'SITUACIONAL', pact: null, source: 'TCE', desc: 'Animate Dead 1/día con slot.' },
]

export const KEY_SPELLS_NO_CONC = [
  {
    name: 'Armor of Agathys',
    slotLvl: 1, type: 'Defensa', ritual: false,
    desc: 'Acción. Ganas 5 PG temp. por nivel de slot (5/10/15…). Mientras dure, cualquier criatura que te golpee en cuerpo a cuerpo recibe el mismo frío como daño. Con Shield activo y alta CA es la combinación más rentable del brujo de melee.',
    tip: 'Escala potente: lanza en slot máximo del brujo para maximizar reacción de daño.',
  },
  {
    name: 'Comprensión de Lenguas',
    slotLvl: 1, type: 'Ritual/Utilidad', ritual: true,
    desc: 'Ritual (10 min sin slot). Durante 1 hora entiendes cualquier idioma hablado o escrito. Sin concentración ni slot si se lanza como ritual.',
    tip: 'Lanza siempre como RITUAL: no gasta slot, domina toda situación de información y negociación.',
  },
  {
    name: 'Shield',
    slotLvl: 1, type: 'Defensa', ritual: false,
    desc: 'Reacción cuando te golpean. +5 CA hasta tu siguiente turno. Nula si el ataque ya falla. Combina con Armor of Agathys: defines si "dejas pasar" para activar el daño frío.',
    tip: 'Lista extendida de Hexblade. Guarda la reacción para decidir: ¿activo Agathys o bloqueo el golpe?',
  },
  {
    name: 'Wrathful Smite',
    slotLvl: 1, type: 'Daño/CC', ritual: false,
    desc: 'Acción adicional antes de atacar. Si golpeas: +1d6 psíquico y el objetivo puede quedar Asustado (SAB CD). Concentración, pero dura mientras el objetivo esté asustado y falle sus tiradas.',
    tip: 'Lista extendida Hexblade. Muy útil contra enemigos de baja SAB o en apertura con ventaja.',
  },
  {
    name: 'Misty Step',
    slotLvl: 2, type: 'Movilidad', ritual: false,
    desc: 'Acción adicional. Teletransporte 30 pies a lugar visible. Sin concentración. Escapa de agarre, reposiciona, flanquea o rompe línea "gratis".',
    tip: 'El slot de nivel 2 más eficiente del brujo. Casi siempre vale más que un slot de daño.',
  },
]

export const CONC_SPELLS = [
  { name: 'Hex',              slotLvl: 1, ctrl: 2, dps: 5, surv: 1, desc: '+1d6 tipo elegido por ataque. Rota cuando el objetivo cae (acción bonus).' },
  { name: 'Darkness',         slotLvl: 2, ctrl: 5, dps: 2, surv: 4, desc: "Con Devil's Sight: ventaja en tus ataques, desventaja en todos los enemigos." },
  { name: 'Hypnotic Pattern', slotLvl: 3, ctrl: 5, dps: 1, surv: 4, desc: 'Incapacita múltiples enemigos. El mejor control de multitud del brujo.' },
  { name: 'Shadow of Moil',   slotLvl: 4, ctrl: 3, dps: 3, surv: 5, desc: 'Ocultación, retribución de fuego. Muy resistente para aguantar daño.' },
  { name: 'Hold Monster',     slotLvl: 5, ctrl: 5, dps: 3, surv: 2, desc: 'Paraliza cualquier criatura. Críticos automáticos en contacto hasta que falle.' },
  { name: 'Banishment',       slotLvl: 4, ctrl: 4, dps: 1, surv: 4, desc: 'Saca al boss del mapa. Tiempo para curar y eliminar secuaces.' },
  { name: 'Forcecage',        slotLvl: 7, ctrl: 5, dps: 1, surv: 3, desc: 'Encierra al boss sin salvación. Termina la lucha si se aplica bien.' },
]
